<?php

/**
 * @file
 * Module file for the Commerce QuickBooks Online module.
 */

/**
 * Implements hook_menu().
 */
function commerce_qbo_menu() {
  $items['admin/commerce/config/qbo'] = array(
    'title' => 'QuickBooks Online',
    'page callback' => 'commerce_qbo_admin_config',
    'access arguments' => array('administer qbo'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'commerce_qbo.admin.inc',
  );
  $items['admin/commerce/config/qbo/menu_proxy'] = array(
    'title' => 'Menu proxy',
    'page callback' => 'commerce_qbo_menu_proxy',
    'access arguments' => array('administer qbo'),
    'type' => MENU_CALLBACK,
    'file' => 'commerce_qbo.admin.inc',
  );
  $items['admin/commerce/config/qbo/connect'] = array(
    'title' => 'Connect to QuickBooks Online',
    'page callback' => 'commerce_qbo_connect',
    'access arguments' => array('administer qbo'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'commerce_qbo.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function commerce_qbo_permission() {
  return array(
    'administer qbo' => array(
      'title' => t('Administer Commerce QuickBooks Online'),
    ),
  );
}
